config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users, except: %i[destroy] do
    resources :document_templates do
      resource :render, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document_template.rb
class DocumentTemplate < ApplicationRecord
  belongs_to :user

  before_save :update_vars
  after_save :update_user_min_vars

  validates :name, presence: true
  validates :liquid_text, presence: true

  def vars
    @vars ||= Liquid::ParseTreeVisitor
      .for(Liquid::Template.parse(liquid_text).root)
      .add_callback_for(Liquid::VariableLookup) { |node|
        [node.name, *node.lookups].join(".")
      }.visit.flatten.compact.uniq
  end

  private

  def update_vars
    self.user_vars = vars.map.with_index { |var, i|
      next unless var.start_with? "mi."
      vars[i] = nil
      var.delete_prefix("mi.")
    }.compact

    self.local_vars = vars.compact
  end

  def update_user_min_vars
    user.update_min_vars
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :document_templates

  def missing_vars?
    (min_vars - vars.keys).any?
  end

  def update_min_vars
    document_templates.map(&:user_vars).flatten.uniq.then { |vars| update(min_vars: vars) }
  end

  def vars_fields
    min_vars.zip(Array(nil)).to_h.merge(vars).to_h
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/document_templates_controller.rb
class DocumentTemplatesController < ApplicationController
  before_action :document_template, only: %i[show edit update destroy]

  def index
    @document_templates = user.document_templates.all
  end

  def new
    @document_template = user.document_templates.build
  end

  def create
    @document_template = user.document_templates.build(document_template_params)

    if @document_template.save
      redirect_to user_document_template_path(user, @document_template)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @document_template.update(document_template_params)
      redirect_to user_document_template_path(user, @document_template)
    else
      render :new
    end
  end

  def destroy
    @document_template.destroy
    redirect_to user_document_templates_path(user)
  end

  private

  def user
    @user ||= User.find(params[:user_id])
  end

  def document_template
    @document_template ||= user.document_templates.find(params[:id])
  end

  def document_template_params
    params.require(:document_template).permit(:name, :liquid_text)
  end
end

app/controllers/renders_controller.rb
class RendersController < ApplicationController
  def create
    @render = DocumentService.render(template: document_template, local_vars: render_params).html_safe
    render "create"
  end

  private

  def render_params
    params.require(:render).permit(local_vars: {}).fetch(:local_vars)
  end

  def document_template
    @document_template ||= user.document_templates.find(params[:document_template_id])
  end

  def user
    @user ||= User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user, only: %i[edit update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_document_templates_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_document_templates_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, vars: {})
  end

  def user
    @user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/document_templates/_document_template.html.erb
<li>
  <h2><%= document_template.name %></h2>
  <%= link_to "Editar", edit_user_document_template_path(@user, document_template) %>
  <%= link_to "Generar Documento", user_document_template_path(@user, document_template) %>
</li>

app/views/document_templates/_form.html.erb
<%= form_with model: [@user, @document_template] do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

  <div class="field">
    <%= f.label :liquid_text %>
    <%= f.text_area :liquid_text %>
  </div>

  <%= f.button type: "submit" %>
<% end %>

app/views/document_templates/edit.html.erb
<%= render "form" %>
<%= link_to "Cancelar", user_document_template_path(@user, @document_template) %>

app/views/document_templates/index.html.erb
<h1><%= @user.email %></h1>
<% if @user.missing_vars? %>
<span>Faltan variables por agregar</span>
<% end %>
<%= link_to "Editar", edit_user_path(@user) %>

<% if @document_templates.any? %>
<ul>
  <%= render @document_templates %>
</ul>
<% end %>

<%= link_to "Crear Template", new_user_document_template_path %>

app/views/document_templates/new.html.erb
<%= render "form" %>
<%= link_to "Cancelar", user_document_templates_path(@user) %>

app/views/document_templates/show.html.erb
<h2><%= @document_template.name %></h2>
<%= link_to "Editar", edit_user_document_template_path(@user, @document_template) %>
<%= link_to "Regresar", user_document_templates_path(@user) %>

<%= form_with url: user_document_template_render_path(@user, @document_template), local: true do %>
  <% @document_template.local_vars.each do |local_var| %>
  <div class="field">
    <%= label_tag "render[local_vars][#{local_var}]", local_var %>
    <%= text_field_tag "render[local_vars][#{local_var}]" %>
  </div>
  <% end %>

  <%= button_tag "Generar", type: :submit %>
<% end %>

<pre><%= @document_template.liquid_text %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Documinion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/renders/create.html.erb
<article class="render">
  <%= @render %>
</article>

app/views/users/_user.html.erb
<li>
  <h2><%= user.email %></h2>
  <%= link_to "Ver", user_document_templates_path(user) %>
</li>

app/views/users/edit.html.erb
<%= form_with model: @user do |f| %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <% @user.vars_fields.each do |name, value| %>
  <div class="field">
    <%= f.label "vars_#{name}", name %>
    <%= text_field_tag "user[vars][#{name}]", value  %>
  </div>
  <% end %>

  <%= f.button type: "submit" %>
<% end %>

<%= link_to "Cancelar", user_document_templates_path(@user) %>

app/views/users/index.html.erb
<ul>
  <%= render @users %>
</ul>

<%= link_to "Agregar Usuario", new_user_path %>

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <%= f.button type: "submit" %>
<% end %>